trigger:
- master
- azure-pipelines

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  displayName: Restore NuGet Packages
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Build Code
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: NuGetCommand@2
  displayName: Package NuGet
  inputs:
    command: 'pack'
    packagesToPack: '**/Xam.SqlHelper.csproj;'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '0'
    patchVersion: '0'

- task: NuGetCommand@2
  displayName: Push NuGet Packages To Private Feed
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '39fa5623-ce15-4ed9-a2ef-637ad0b5ca00'